name: Deploy to S3

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::471112515426:role/Github_to_S3_role
        aws-region: us-east-1  # Change to your region if different

    - name: Sync S3 bucket
      run: |
        aws s3 sync . s3://khanh-tran-cloud-resume --follow-symlinks --delete --exclude '.git/*' --size-only
